# Define the number of particles
num_particles: 50
# Define the starting positions of the particles
initial_x_min: -10
initial_x_max: 10
initial_y_min: -10
initial_y_max: 10
initial_theta_min: 0
initial_theta_max: 6.28319

# Define a variance for the particles motion model
var_v: 0.1
var_w: 0.1

# Define gaussian for the sensor model
sigma: 3.0