# Define the number of particles
num_particles: 1000
initial_x_min: -10.0
initial_x_max: 10.0
initial_y_min: -10.0
initial_y_max: 10.0
initial_theta_min: 0.0
initial_theta_max: 6.28319
var_v: 5.0
var_w: 1.0
sigma: 1.00
percentage_rand_particles: 0.1